sf_analytics:
  outputs:
    dev:
      account: tpfiwgg-og99352
      database: analytics
      password: "{{ env_var( 'DBT_PASSWORD')}}"
      role: accountadmin
      schema: staging
      threads: 4
      type: snowflake
      user: "{{ env_var( 'DBT_USER')}}"
      warehouse: compute_wh
  target: dev