sf_analytics:
  outputs:
    dev:
      account: tpfiwgg-og99352
      database: analytics
      password: 653508devph@Snowflake
      role: dbt_role
      schema: staging
      threads: 4
      type: snowflake
      user: devph
      warehouse: dbt_wh
  target: dev

# sf_analytics:
#   outputs:
#     dev:
#       type: snowflake
#       account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
#       user: "{{ env_var('DBT_USER') }}"
#       password: "{{ env_var('DBT_PASSWORD') }}"
#       role: dbt_role
#       database: analytics
#       warehouse: dbt_wh
#       schema: staging
#       threads: 4
#     ci:
#       type: snowflake
#       account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
#       user: "{{ env_var('DBT_USER') }}"
#       password: "{{ env_var('DBT_PASSWORD') }}"
#       role: dbt_role
#       database: analytics
#       warehouse: dbt_wh
#       schema: staging
#       threads: 4
#     prod:
#       type: snowflake
#       account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
#       user: "{{ env_var('DBT_USER') }}"
#       password: "{{ env_var('DBT_PASSWORD') }}"
#       role: dbt_role
#       database: analytics
#       warehouse: dbt_wh
#       schema: staging
#       threads: 4
#   target: dev
