pull_request:
  branches: ["feature/PROJ-01-warehouse"]

workflow_dispatch:

jobs:
	build-and-deploy:
	  runs-on: ubuntu-latest
	  env:
      DBT_USER=devph
      DBT_PASSWORD=653508devph@Snowflake
      SNOWFLAKE_ACCOUNT=tpfiwgg-og99352

	  steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt
        run: pip3 install dbt-snowflake

      - name: Deploy & Test Models (dev)
        run: dbt-build --profiles-dir . --target dev
	   