pull_request:
  branches: ["main"]

workflow_dispatch:

jobs:
	build-and-deploy:
	  runs-on: ubuntu-latest
	  env:
      DBT_USER: ${{ secrets.DBT_USER }}
       
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}

	  steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt
        run: pip3 install dbt-snowflake

      - name: Deploy & Test Models (dev)
        run: dbt-build --profiles-dir . --target dev

# name: Test CI

# on: [push, pull_request]

# jobs:
#   test:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.x'
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install dbt-core dbt-snowflake
#     - name: Run dbt run
#       env:
#         DBT_PROFILES_DIR: ${{ secrets.DBT_PROFILES_DIR }}
#         SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
#         SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
#         SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
#         SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
#         SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
#         SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
#       run: dbt run
#     - name: Run dbt tests
#       env:
#         DBT_PROFILES_DIR: ${{ secrets.DBT_PROFILES_DIR }}
#         SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
#         SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
#         SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
#         SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
#         SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
#         SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
#       run: dbt test



	   